services:
  crud-app-grpc:
    image: crud-app-grpc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:8080"
  grpc-crud-database:
    container_name: grpc-crud-database
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ./Docker/postgres/data:/var/lib/postgresql/data
